sudo: false
language: node_js
node_js: "8"
before_install:
  - npm install -g coffee-script
  - npm install path@0.11
  - npm install util
  - npm install -g phantomjs@1.9.20
  - cake build
script: cake test
notifications:
  email: false
branches:
  except:
    - experimental
    - 1.43
    - commands
